### PR TITLE
Clean up dependencies as reported by dependency:analyze

### PR DESCRIPTION
**Pull request by michael-o**
Maven Surefire maintainer here...

### CODE REVIEW

**Comment by ahoehma** [comment]
Alright ... I need to combine the changes into my https://github.com/fabriciorby/maven-surefire-junit5-tree-reporter/pull/53 ... use of plexus-container-default is deprecated!

**Comment by michael-o** [comment]
The second commit is also imperative because the actual issue in #52 is caused by this. This extension shall only use depenencies provided by the Maven Surefire Plugin at runtime and not have your own. That will result in a mismatch. Up into now it was just luck that it worked.

**Review by ahoehma — COMMENTED** [review]
@michael-o  and I we analyzed the problem today together and from my point of view these changes are fine.

**Comment by michael-o** [comment]
@cstamas @slawekjaranowski This is a good example when deps aren't being put into `provided` scope.

**Pull request merged**
